package tests.integration;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.core.io.ClassPathResource;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.web.servlet.MockMvc;
import tests.support.PostgresTestContainer;
import tests.support.TestApplicationConfiguration;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Regressão do arranque contra uma base com o esquema antigo.
 *
 * <p>Reproduz a falha reportada em produção: {@code tb_user} já povoada e sem a
 * coluna {@code active}. O {@code ddl-auto: update} do Hibernate não a consegue
 * criar, porque emite {@code add column active boolean not null} sem default, e o
 * PostgreSQL recusa esse comando numa tabela com linhas. Sem a migração de
 * arranque, a aplicação arrancava na mesma e só rebentava mais tarde, com
 * {@code column u1_0.active does not exist}.
 *
 * <p>Usa uma base própria, criada dentro do mesmo contêiner, para não mexer no
 * esquema que os restantes testes partilham. O {@code ddl-auto} é
 * {@code update} e não {@code create}: com {@code create} o Hibernate criaria a
 * tabela já completa e o teste não provaria nada.
 */
@SpringBootTest
@AutoConfigureMockMvc
@ContextConfiguration(classes = TestApplicationConfiguration.class)
@DisplayName("Migração da coluna active")
class ActiveColumnMigrationIntegrationTest {

    private static final String BASE = "supervisor_legacy";
    private static final String SCRIPT = "db/migration/V1__add_active_to_tb_user.sql";
    private static final String SENHA = "123456";

    /** O esquema de antes da coluna {@code active}, com as mesmas tabelas. */
    private static final String TB_USER_LEGADO = """
            create table tb_user (
                id bigint generated by default as identity primary key,
                email varchar(255) unique,
                name varchar(255),
                password varchar(255),
                profile varchar(255)
            )
            """;

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbc;

    @Autowired
    private PasswordEncoder encoder;

    @DynamicPropertySource
    static void propriedades(DynamicPropertyRegistry registry) {
        var container = PostgresTestContainer.container();
        prepararBaseAntiga();

        registry.add("spring.datasource.url", () -> urlDaBase(container.getJdbcUrl(), BASE));
        registry.add("spring.datasource.username", container::getUsername);
        registry.add("spring.datasource.password", container::getPassword);
        registry.add("spring.datasource.driver-class-name", container::getDriverClassName);
        registry.add("spring.jpa.hibernate.ddl-auto", () -> "update");
        registry.add("spring.jpa.show-sql", () -> "false");
        registry.add("spring.jpa.open-in-view", () -> "false");
        registry.add("api.security.token.secret", () -> "chave-de-teste-super-visor-0123456789-abcdef");
    }

    /**
     * Recria a base legada: a tabela antiga e duas contas. A tabela fica com
     * linhas de propósito, porque é a existência delas que faz o PostgreSQL
     * rejeitar o {@code ALTER TABLE} sem default.
     */
    private static void prepararBaseAntiga() {
        var container = PostgresTestContainer.container();
        executar(container.getJdbcUrl(), "drop database if exists " + BASE);
        executar(container.getJdbcUrl(), "create database " + BASE);

        String url = urlDaBase(container.getJdbcUrl(), BASE);
        executar(url, TB_USER_LEGADO);
        executar(url, """
                insert into tb_user (email, name, password, profile) values
                    ('admin@teste.com', 'Administrador', 'hash-admin', 'SUPERVISOR'),
                    ('joao@teste.com',  'João',        'hash-joao',  'ANALIST')
                """);
    }

    private static void executar(String url, String sql) {
        try (Connection connection = DriverManager.getConnection(
                url, PostgresTestContainer.container().getUsername(),
                PostgresTestContainer.container().getPassword());
             Statement statement = connection.createStatement()) {
            statement.execute(sql);
        } catch (Exception e) {
            throw new IllegalStateException("Falha ao preparar a base legada: " + sql, e);
        }
    }

    /** Troca o nome da base mantendo o servidor, a porta e os parâmetros. */
    private static String urlDaBase(String urlPadrao, String base) {
        int interrogacao = urlPadrao.indexOf('?');
        String semParametros = interrogacao < 0 ? urlPadrao : urlPadrao.substring(0, interrogacao);
        String comBase = semParametros.substring(0, semParametros.lastIndexOf('/') + 1) + base;
        return interrogacao < 0 ? comBase : comBase + urlPadrao.substring(interrogacao);
    }

    /**
     * O script sem comentários: o que interessa ao PostgreSQL é o que é
     * executado, e o ficheir descreve precisamente o `DO $$` que não pode usar.
     */
    private static String instrucoesDoScript() {
        return lerScript().replaceAll("(?m)^\\s*--.*$", "");
    }

    /**
     * Corre o script instrução a instrução, como o Spring faz: o driver não
     * aceita várias instruções num {@code execute} só, e o ficheiro tem duas.
     */
    private static void executarScript(String url, String script) {
        for (String instrucao : script.split(";")) {
            if (!instrucao.isBlank()) {
                executar(url, instrucao.trim());
            }
        }
    }

    private static String lerScript() {
        try (InputStream stream = new ClassPathResource(SCRIPT).getInputStream()) {
            return new String(stream.readAllBytes(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new IllegalStateException("Script de migração ausente: " + SCRIPT, e);
        }
    }

    @Test
    @DisplayName("a aplicação arranca e a coluna active passa a existir")
    void aColunaActiveExisteDepoisDoArranque() {
        Integer colunas = jdbc.queryForObject("""
                select count(*) from information_schema.columns
                where table_schema = 'public' and table_name = 'tb_user' and column_name = 'active'
                """, Integer.class);

        assertThat(colunas).isEqualTo(1);
    }

    @Test
    @DisplayName("a coluna é NOT NULL, para não voltar a haver contas sem estado")
    void aColunaEhNotNull() {
        String isNullable = jdbc.queryForObject("""
                select is_nullable from information_schema.columns
                where table_schema = 'public' and table_name = 'tb_user' and column_name = 'active'
                """, String.class);

        assertThat(isNullable).isEqualTo("NO");
    }

    @Test
    @DisplayName("as contas existentes ficam ativas, sem backfill manual")
    void asContasExistentesFicamAtivas() {
        Integer inativas = jdbc.queryForObject(
                "select count(*) from tb_user where active is not true", Integer.class);

        assertThat(inativas).isZero();
    }

    @Test
    @DisplayName("a migração só preenche o que o PostgreSQL insere: um registo novo nasce ativo")
    void umRegistoNovoNasceAtivo() {
        jdbc.update("insert into tb_user (email, name, password, profile) "
                + "values ('nova@teste.com', 'Nova', 'x', 'ANALIST')");

        Boolean ativa = jdbc.queryForObject(
                "select active from tb_user where email = 'nova@teste.com'", Boolean.class);

        assertThat(ativa).isTrue();
    }

    @Test
    @DisplayName("consultar a entidade já não falha com 'column u1_0.active does not exist'")
    void consultarUtilizadorNaoFalha() {
        Integer total = jdbc.queryForObject("select count(*) from tb_user", Integer.class);

        assertThat(total).isGreaterThanOrEqualTo(2);
    }

    @Test
    @DisplayName("a migração é repetível: voltar a correr o script não falha")
    void aMigracaoEhRepetivel() {
        jdbc.execute("alter table tb_user drop column active");
        jdbc.update("update tb_user set name = 'Administrador' where email = 'admin@teste.com'");

        executarScript(urlDaBase(PostgresTestContainer.container().getJdbcUrl(), BASE),
                instrucoesDoScript());

        Integer ativos = jdbc.queryForObject(
                "select count(*) from tb_user where active is true", Integer.class);
        assertThat(ativos).isEqualTo(2);
    }

    @Test
    @DisplayName("depois da migração, o login funciona com uma conta que já existia")
    void oLoginFuncionaDepoisDaMigracao() throws Exception {
        jdbc.update("update tb_user set password = ? where email = 'admin@teste.com'",
                encoder.encode(SENHA));

        // O endpoint devolve o token em texto simples, não um objeto JSON.
        String token = mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"email":"admin@teste.com","password":"%s"}
                                """.formatted(SENHA)))
                .andExpect(status().isOk())
                .andReturn().getResponse().getContentAsString();

        assertThat(token).isNotBlank();
    }

    @Test
    @DisplayName("uma conta desativada é bloqueada no login, e não só nas rotas")
    void contaDesativadaNaoEntraNoLogin() throws Exception {
        jdbc.update("update tb_user set password = ?, active = false where email = 'joao@teste.com'",
                encoder.encode(SENHA));

        mockMvc.perform(post("/api/auth/login")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"email":"joao@teste.com","password":"%s"}
                                """.formatted(SENHA)))
                .andExpect(status().isUnauthorized())
                .andExpect(jsonPath("$.error").value("Unauthorized"));
    }

    @Test
    @DisplayName("o script de migração só tem DDL simples, sem blocos procedurais")
    void oScriptSoTemDdlSimples() {
        String sql = instrucoesDoScript();

        // O leitor de scripts do Spring parte o ficheiro em `;` e não percebe
        // dollar-quoting do PostgreSQL. Um `DO $$ ... $$` seria truncado e a
        // aplicação deixava de arrancar, por isso isto é um teste de regressão.
        assertThat(sql).doesNotContain("$$");
        assertThat(sql).doesNotContainIgnoringCase("do begin");
        assertThat(sql).isNotBlank();
    }
}
