spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/supervisor
    username: supervisor
    password: supervisor
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
api:
  security:
    token:
      secret: "***SEGREDO-REMOVIDO-DO-HISTORICO***"
